apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-pixa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-pixa
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-pixa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-pixa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-pixa
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lcfp-tenant/rhtap-demo-app/hacbs-test-project-pixa@sha256:cede013ccb83c1829b5eb636f7c642d5276d192fda04072ea93a1135f659cee3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
